---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
  - list
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - list
- apiGroups:
  - grpc-mock.grakh.com
  resources:
  - grpcmocks
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - grpc-mock.grakh.com
  resources:
  - grpcmocks/finalizers
  verbs:
  - update
- apiGroups:
  - grpc-mock.grakh.com
  resources:
  - grpcmocks/status
  verbs:
  - get
  - patch
  - update
